version: "3.8"
services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c 'npm run start:dev'
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ".:/code"
    working_dir: /code/backend
